### ISSUE TITLE
dataset preparation

### ISSUE THREAD

**Issue by joaquinsalas** [pfnet-research/CSDI_T#3]
Hello. Thanks for making your code available.
Would you please tell me how should I prepare my dataset (currently a CSV file) to use your code?

Thanks, Joaquin

**Comment by joshua-shuhan** [comment]
Hi! Thanks for your interest in our work. The basic guideline is as follows.
1. First, it is better to create a folder to store the data (e.g., folder `data_{dataset_name}` in the repo).
2. You can then create a py file to process the dataset (e.g., `dataset_breast.py`, `dataset_census_onehot.py` in the repo). If the dataset only contains numerical variables, I believe the `dataset_breast.py` file is a good example to follow.
3. Finally, create a file to run the experiment (e.g., `exe_breast.py` in the repo).

Most preparation works can be done by copy and paste. But be careful about missing values handling (e.g., Line 12 in `dataset_breast.py`) and whether your dataset contains some columns that need to be dropped beforehand.

Don't hesitate to ask if you have any further questions : )
