### ISSUE TITLE
Store the dataset after imputation

### ISSUE THREAD

**Issue by kuiyuanshao** [pfnet-research/CSDI_T#4]
Hi there,

I am wondering how to store the dataset after the imputation? I tried to use the model.evaluate() and store the "samples" object, but got very large and werid values compared to original data.

Thank you in advance!

**Comment by joshua-shuhan** [comment]
Hi, thanks for your interest in our work.
Have you tried to uncomment codes [here](https://github.com/pfnet-research/TabCSDI/blob/fbee1b13986d976e1ec4c9bf80bfaccc1dd00117/src/utils_table.py#L165)?

**Comment by kuiyuanshao** [comment]
Hi Joshua,

I guess I have figured out how to save the dataset, thank you for your quick reply.
